### ISSUE TITLE
Logs don't tail after "Brightscript Debugger>" appears in console output

### ISSUE THREAD

**Issue by sjbarag** [hulu/roku-dev-cli#8]
After experiencing a crash (or legitimately using the BrightScript debugger via `telnet ip.add.re.ss 8085`), the first few installed builds don't result in logs getting printed.  It appears that connecting to a Roku over `telnet` (like this CLI does) always returns a few lines of history.

Any way to make this not happen?  I wind up `^C`ing the script after it installs and just running `telnet` directly, so something like `roku --install-only ip.add.re.ss && telnet ip.add.re.ss 8085` would be lovely.  Or even just letting the logs continue to flow after detecting `Brightscript Debugger>`?

**Comment by strattonbrazil** [comment]
Yes, exiting the script has become more of a pain point than a feature now.  We should just remove the check altogether.
